export const SELECT_MODEL = 'SELECT_MODEL';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';

export const LOAD_EMPLOYEES = 'LOAD_EMPLOYEES';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_PHOTO = 'UPDATE_EMPLOYEE_PHOTO';

export const LOAD_SERVICES = 'LOAD_SERVICES';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';

export const LOAD_SHIFTS = 'LOAD_SHIFTS';
export const CREATE_SHIFT = 'CREATE_SHIFT';
export const UPDATE_SHIFT = 'UPDATE_SHIFT';

export const LOAD_SCHEDULES = 'LOAD_SCHEDULES';
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';

export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
