export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const TOGGLE_LEFT_PANE = 'TOGGLE_LEFT_PANE';
export const TOGGLE_LEFT_PANE_BUTTON_VISIBILITY = 'TOGGLE_LEFT_PANE_BUTTON_VISIBILITY';
